networks:
  caddy_net:
    external: true

services:
  siyuan:
    image: ghcr.io/eightdoor/unlock-siyuan:latest
    container_name: siyuan-unlock
    ports:
      - "0.0.0.0:6806:6806"
    volumes:
      - /home/mikuserver/disk1/dev/siyuan:/siyuan/workspace:Z
    command: ["--workspace=/siyuan/workspace", "--accessAuthCode=39miku!Hatsune"]
    restart: always
    networks:
      - caddy_net
    labels:
      caddy: siyuan.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 6806}}"
