networks:
  proxy-network:
    external: true


services:
  siyuan:
    image: ghcr.io/eightdoor/unlock-siyuan:latest
    container_name: siyuan-unlock
    ports:
      - "0.0.0.0:6806:6806"
    volumes:
      - /home/mikuserver/disk1/dev/siyuan:/siyuan/workspace:Z
    command: ["--workspace=/siyuan/workspace", "--accessAuthCode=39miku!Hatsune"]
    restart: always
    networks:
      - proxy-network

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.siyuan.rule=Host(`siyuan.pashahatsune.pp.ua`)"
      - "traefik.http.routers.siyuan.entrypoints=websecure"
      - "traefik.http.routers.siyuan.tls=true"
      - "traefik.http.routers.siyuan.tls.certresolver=le"
