version: "3.3"

networks:
  caddy_net:
    external: true

services:
  alist:
    image: "xhofe/alist:beta"
    container_name: alist
    restart: always
    userns_mode: keep-id
    entrypoint: ["/opt/alist/alist", "server"]
    security_opt:
      - label=disable
    networks:
      - caddy_net
    labels:
      caddy: alist.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 5244}}"
    volumes:
      - /home/miku/disk1/dev/alist/data:/opt/alist/data:Z
      - /home/mikuserver:/home/mikuserver:Z
