version: "3.3"

networks:
  proxy-network:
    external: true

services:
  alist:
    image: "xhofe/alist:beta"
    container_name: alist
    restart: always
    userns_mode: keep-id
    # Запускаем бинарник напрямую, минуя скрипт с chown/su-exec
    entrypoint: ["/opt/alist/alist", "server"]
    security_opt:
      - label=disable
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alist.rule=Host(`alist.pashahatsune.pp.ua`)"
      - "traefik.http.routers.alist.entrypoints=websecure"
      - "traefik.http.routers.alist.tls=true"
      - "traefik.http.routers.alist.tls.certresolver=le"
      - "traefik.http.services.alist.loadbalancer.server.port=5244"
    volumes:
      - /home/miku/disk1/dev/alist/data:/opt/alist/data:Z
      - /home/mikuserver:/home/mikuserver:Z

