version: '3.8'
networks:
  proxy-network:
    external: true
services:
  tuwunel:
    image: jevolk/tuwunel:latest
    container_name: tuwunel
    restart: always
    # ИСПОЛЬЗУЕМ СЕТЬ ХОСТА: это решит проблему с DNS и скоростью
    networks:
      - proxy-network
    


    security_opt:
      - label=disable
    volumes:
      - /home/mikuserver/disk1/dev/tuwunel/tuwunel.toml:/etc/tuwunel.toml:ro,Z
      - /home/mikuserver/disk1/dev/tuwunel/matrix_db:/var/lib/tuwunel:Z
    environment:
      - TUWUNEL_CONFIG=/etc/tuwunel.toml  
    # Больше не нужны ports: и dns:, так как мы в сети хоста

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.tuwunel.rule=Host(`pashahatsune.pp.ua`)"
      - "traefik.http.routers.tuwunel.entrypoints=websecure"
      - "traefik.http.routers.tuwunel.tls=true"
      - "traefik.http.routers.tuwunel.tls.certresolver=le"

      # - "traefik.http.services.alist.loadbalancer.server.port=5244"