version: '3.8'
networks:
  caddy_net:
    external: true
services:
  tuwunel:
    image: jevolk/tuwunel:latest
    container_name: tuwunel
    restart: always
    networks:
      - caddy_net
    security_opt:
      - label=disable
    volumes:
      - /home/mikuserver/disk1/dev/tuwunel/tuwunel.toml:/etc/tuwunel.toml:ro,Z
      - /home/mikuserver/disk1/dev/tuwunel/matrix_db:/var/lib/tuwunel:Z
    environment:
      - TUWUNEL_CONFIG=/etc/tuwunel.toml
    labels:
      caddy: pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 8080}}"
