services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mikuserver/disk1/dev/homarr:/appdata:Z
    environment:
      - SECRET_ENCRYPTION_KEY=060a836266a973ffbbbdb9c3770aacf5ebd117b9c7351488e4380c58dfcce616
    labels:
      caddy: homepage.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
