version: "3.2"

networks:
  caddy_net:
    external: true

services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    userns_mode: "keep-id"
    security_opt:
      - label=disable
    volumes:
      - /home//disk1/dev/backrest:/data:z
      - /mnt/disk1/dev/backrest/config:/config:z
      - /mnt/disk1/dev/backrest/cache:/cache:z
      - /mnt/disk1/dev:/userdata/mikuserver/dev:ro
      - /mnt/disk1/dev:/userdata/disk1/dev:ro
      - /mnt/disk1/backups:/repos/backups
      - /mnt/disk1/backups:/repos/disk1-backups
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TZ=Europe/Moscow
    networks:
      - caddy_net
    restart: always
    labels:
      caddy: backrest.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 9898}}"
    ports:
      - 9898:9898
