version: "3.7"

networks:
  proxy-network:
    external: true



services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    volumes:
      - /home/miku/disk1/dev/bitwarden/bitwarden/data:/data:Z
      # Монтируем всю папку letsencrypt по тому же пути, что и на хосте
    env_file:
      - config.env
    ports:
      - "2544:80"
    restart: always
    networks:
      - proxy-network
