version: "3.7"

networks:
  caddy_net:
    external: true

services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    volumes:
      - /home/mikuserver/disk1/dev/bitwarden/bitwarden/data:/data:Z
    env_file:
      - /home/mikuserver/disk1/dev/bitwarden/bitwarden/config.env
    labels:
      caddy: btw.pashahatsune.pp.ua
      caddy.@block: "not remote_ip 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 fd00::/8"
      caddy.respond: "@block 404"
      caddy.reverse_proxy: "{{upstreams 80}}"
    ports:
      - "2544:80"
    restart: always
    networks:
      - caddy_net
