networks:
  caddy_net:
    external: true

services:
  postgres:
    image: postgres:16-alpine
    env_file: /mnt/disk1/dev/linkwarden/.env
    restart: always
    volumes:
      - /mnt/disk1/dev/linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      - caddy_net
  linkwarden:
    env_file: /mnt/disk1/dev/linkwarden/.env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    labels:
      caddy: linkwarden.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy_net
    ports:
      - 3000:3000
    volumes:
      - /mnt/disk1/dev/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    networks:
      - caddy_net
    env_file:
      - /mnt/disk1/dev/linkwarden/.env
    volumes:
      - /mnt/disk1/dev/linkwarden/meili_data:/meili_data
