networks:
  caddy_net:
    external: true

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/mikuserver/disk1/dev/caddy/data:/data:Z
      - /home/mikuserver/disk1/dev/caddy/config:/config:Z
    networks:
      - caddy_net
    labels:
      caddy_email: pashahatsune@gmail.com
