services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    volumes:
      - /mnt/disk1/dev/uptime-kuma/data:/app/data
    environment:
      - TZ=UTC
      - UMASK=0022
    networks:
      - caddy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      caddy: uptime.pashahatsune.pp.ua
      caddy.reverse_proxy: "{{upstreams 3001}}"

networks:
  caddy_net:
    external: true
